# Generated by Django 2.2.5 on 2019-11-02 19:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ate_employees', '0002_auto_20191018_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ate_employees',
            name='work',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
