# Generated by Django 2.2.5 on 2019-11-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ate_employees', '0003_auto_20191102_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ate_employees',
            name='work',
            field=models.UUIDField(null=True),
        ),
    ]
