language:
  python

python:
  - '3.7.3'

install:
  - pip install -r requirements.txt

script:
  - cd ATE
  - coverage run manage.py test
  #- coverage report -m

  - cd ../gateway
  - coverage run manage.py test
  #- coverage report -m

  - cd ../Nuke
  - coverage run manage.py test
  #- coverage report -m

  - cd ../Payment
  - coverage run manage.py test
  #- coverage report -m

  - cd ../WorkList
  - coverage run manage.py test
  #- coverage report -m