# Generated by Django 2.2.5 on 2019-11-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20191127_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paylist',
            name='coeff',
            field=models.CharField(max_length=10),
        ),
    ]
